[package]
name = "pnglitch-cli"
version = "0.1.0"
authors = ["Christopher Shea <cmshea@gmail.com>"]

[dependencies]
clap = "2.33.3"
png = "0.16.8"
pnglitch-core = { path = "../pnglitch-core" }
rand = "0.7.3"
